config/routes.rb
Temp::Application.routes.draw do

  devise_for :users

  root :to => 'gigs#index'

  resources :gigs do
    resources :budget_items
    resources :expense_items
  end

  resources :contacts

end

app/models/budget_item.rb
class BudgetItem < ActiveRecord::Base
  belongs_to :gig
  belongs_to :user
  attr_accessible :amount, :label, :positive, :gig_id
end

app/controllers/budget_items_controller.rb
class BudgetItemsController < ApplicationController

  before_filter :find_gig

  def new
    @items = BudgetItem.find_all_by_gig_id(@gig.id)
    if @items.empty?
      @budget = BudgetItem.new(:gig_id => @gig.id, :label => "Total Budget", :positive => true, :amount => @gig.total_budget)
    else
      @budget = BudgetItem.new(:gig_id => @gig.id, :label => "New Item", :positive => true, :amount => 0)
    end

    if @budget.save
      flash[:notice] = "Budget updated!"
      redirect_to edit_gig_path(@gig.id, @budget.id, :form => "budgets")
    else
      flash[:notice] = "Budget NOT saved."
      redirect_to gig_path
    end
  end

  def create
    if @budget.save
      flash[:notice] = "Budget updated!"
      redirect_to edit_gig_budget_item_path(@gig.id, @budget.id)
    else
      flash[:notice] = "Budget NOT saved."
      redirect_to gig_path
    end
  end

  def edit
    @items = BudgetItem.find_all_by_gig_id(@gig.id)
    redirect_to new_gig_budget_item_path if @items.empty?
  end

  def update
    @items = BudgetItem.find_all_by_gig_id(@gig.id)
    @items.each {|i| i.save! }
  end

  def show
    flash[:notice] = "Budget saved!"
    redirect_to edit_gig_budget_item_path(@gig.id)
  end

  def destroy
    @item = BudgetItem.find(params[:id])
    @item.destroy
    flash[:notice] = "Item deleted."
    redirect_to edit_gig_path(@gig.id, :form => "budgets")
  end

private

  def find_gig
    @gig = Gig.find(params[:gig_id])
  end

end

app/views/budget_items/_fields.html.erb
<div class="clearfix">
  <table>
    <tr class="budget_container">
      <td>
        <%= f.label :label, "Income" %>
        <%= f.text_field :label %>
      </td>
      <td>
        <%= f.label :amount, "Amount" %>
        <%= f.text_field :amount, :class => "budget-field", :value => (number_with_precision(f.object.amount, :precision => 2 || 0)) %>
      </td>
      <td class="short">
        <%= f.label :_destroy, "Delete", :style => "margin-left:25%" %>
        <%= f.check_box :_destroy, :style => "margin-left:38%" %>
      </td>
    </tr>
  </table>
</div>

app/views/budget_items/new.html.erb
<% form_for(@budget) do |f| %>
<%= f.error_messages %>

<p>
  <%= f.label :total_budget %>
  <%= f.text_field :total_budget %>
</p>

<%= f.submit "Save Budget" %>

<% end %>

app/views/budget_items/show.html.erb
This is the budget show, but we're not going to use it.

app/views/budget_items/update.html.erb
<% @items.each do |item| %>

<%= form_tag(gig_budget_path, :method => 'put') %>
  <div>
    <%= text_field_tag "Item", item.label %>
    <%= text_field_tag "Amount", item.amount %>
  </div>
<% end %>

<br />
<%= submit_tag "Save Budget" %>