config/routes.rb
Temp::Application.routes.draw do

  devise_for :users

  root :to => 'gigs#index'

  resources :gigs do
    resources :budget_items
    resources :expense_items
  end

  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :notes, :phone, :user_id
  belongs_to :user
  has_and_belongs_to_many :gigs
  validates :first_name, :presence => true

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def index
		if current_user
		  @contacts = Contact.where(:user_id => current_user.id)
    else
    	flash.keep
      redirect_to new_user_session_path
    end
	end

	def new
		@contact = Contact.new(:user_id => current_user.id)
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.user_id = current_user.id

		if @contact.save
			flash[:notice] = "Contact saved! (Praise Jesus!)"
			redirect_to contacts_path
		else
			flash[:alert] = "Contact not saved (Hail Satan!)"
			render :action => "new"
		end
	end

	def show
		@contact = Contact.find(params[:id])
	end

	def destroy
		@contact = Contact.find(params[:id])
    @contact.destroy
    flash[:notice] = "Contact deleted!"
    redirect_to contacts_path
	end

	def edit
		@contact = Contact.find(params[:id])
	end

	def update
		@contact = Contact.find(params[:id])
		if @contact.update_attributes(params[:contact])
      flash[:notice] = "Contact saved!"
      redirect_to @contact
    else
      flash[:alert] = "Contact NOT saved."
      render :action =>"edit"
    end
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
<%= f.error_messages %>

<div class="full clearfix">
  <div class="six columns">
    <p>
      <%= f.label :first_name, "First Name" %>
      <%= f.text_field :first_name %>
    </p>

    <p>
      <%= f.label :last_name, "Last Name" %>
      <%= f.text_field :last_name %>
    </p>

    <p>
      <%= f.label :phone, "Contact Phone" %>
      <%= f.text_field :phone %>
    </p>

    <p>
      <%= f.label :email, "Contact Email" %>
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.label :notes, "Notes" %>
      <%= f.text_area :notes %>
    </p>

  </div>
</div>

<br>

<%= f.submit "Save Contact", :class => "button" %>

<% end %>

app/views/contacts/edit.html.erb
<h2>Editing contact</h2>


    <%= render "form" %>

<br/><br/>

app/views/contacts/index.html.erb
<h2>Contacts</h2>
<table>
  <% @contacts.each do |contact| %>
    <tr>
      <td class="bold-table"><%= link_to contact.first_name + " " + contact.last_name, contact %></td>
      <td class="short">
        <div class="button tiny">
          <%= link_to "Edit", edit_contact_path(contact) %>
        </div>
        <div class="button tiny">
          <%= link_to "Delete", contact_path(contact), :method => :delete, :confirm => "Are you sure?" %>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<div class="button"><%= link_to "New Contact", new_contact_path %></div>

app/views/contacts/new.html.erb
<h2>Create Contact</h2>

<%= render "form" %>

app/views/contacts/show.html.erb
<h2><%= @contact.first_name %> <%= @contact.last_name %></h2>

<div class="full clearfix">
  <div class="six columns">
      <span class="subtext2">Email : </span><br />
      <span><%= @contact.email %></span><br /><br />

      <span class="subtext2">Phone : </span><br />
      <span><%= @contact.phone %></span><br /><br />

      <span class="subtext2">Notes : </span><br />
      <span><%= simple_format(@contact.notes) %></span><br /><br /><br />
  </div>
</div>

<div class="button small"><%= link_to "Edit Contact", edit_contact_path(@contact) %></div>