config/routes.rb
Temp::Application.routes.draw do

  devise_for :users

  root :to => 'gigs#index'

  resources :gigs do
    resources :budget_items
    resources :expense_items
  end

  resources :contacts

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Giggerator</title>
      <%= stylesheet_link_tag    "application", :media => "all" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
    </head>
    <body>
      <div id="logo">
        <a href="/"><img src="/assets/giggerator_logo_transparent.png" /></a>
        <div class="sign-in">
          <% if user_signed_in? %>
            Signed in as <%= current_user.email %> |
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path %> or
            <%= link_to "Sign in", new_user_session_path %>
          <% end %>
        </div>
      </div>

      <% flash.each do |key, value| %>
      	<div class='flash' id='<%=key %>'>
      		<%= value %>
      	</div>
      <% end %>

      <div id="main">

          <nav>

            <% if user_signed_in? %>
              <div class="button"><a href="/">My Gigs</a></div>
            	<div class="button"><%= link_to "Create Gig", new_gig_path(:form => "properties") %></div>
            	<div class="button"><%= link_to "Contacts", contacts_path %></div>
            <% end %>

          </nav>
        <%= yield %>
      </div>

    </body>
  </html>